[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eigenlabs-protocol-apis"
version = "0.1.0"
description = "Eigenlabs Protocol APIs grpc clients"
requires-python = ">=3.7"
dependencies = [
    "grpcio>=1.32.0",
    "protobuf>=3.15.0",
]
